In [ ]:
# This notebook reads a (surface) configuration in the lammps-dump-text format and adds an arbitrary number of ammonia molecules on top of the surface.
# Requires ASE https://wiki.fysik.dtu.dk/ase/

In [1]:
from ase.build import molecule
from ase import Atoms
from ase.io import read,write
from ase.visualize import view
import numpy as np
import os

In [5]:
config_file="../surface/384_atoms/Li2NH_384_20NH2.lmp".format(j)
config_orig=read(config_file,format='lammps-dump-text')
cell_arrays=config_orig.get_cell()
print(cell_arrays)
    
n_to_add=2 #how many ammonia molecules to be added
config=config_orig

bx_min= 0#cell_arrays[0,0]/8
bx_max= 8#cell_arrays[0,0]-bx_min
by_min= 0 #cell_arrays[1,1]/8
by_max= 8# cell_arrays[1,1]-by_min

for i in range (0,n_to_add):
    r_x=np.random.uniform(bx_min,bx_max)
    r_y=np.random.uniform(by_min,by_max)
    r_z=np.random.uniform(cell_arrays[2,2]-8.0,cell_arrays[2,2]-7.5)
    print([r_x,r_y,r_z])
    new_mol=molecule('NH3')
    pos=new_mol.get_positions() #4x3 matrix
    for a in range (0,4):
        pos[a]+=[r_x,r_y,r_z]
    print(pos)
    new_mol.set_positions(pos)
    new_system=config+new_mol
    config=new_system
    
config.set_cell(cell_arrays)
fileout="Li2NH_392_20NH2_2NH3.lmp"
write(fileout,config,format='lammps-data')
os.system("awk <"+fileout+" '{if($2==4) print $1,2,$3,$4,$5; else print}' > tmp && mv tmp "+fileout)

Cell([[14.320800000000002, 0.0, 0.0], [-7.1604, 12.402177, 0.0], [0.0, 0.0, 30.0]])
[6.083656007907015, 6.3588789245920525, 22.116154608436133]
[[ 6.08365601  6.35887892 22.23264361]
 [ 6.08365601  7.29860992 21.84434661]
 [ 6.89748701  5.88901392 21.84434661]
 [ 5.26982501  5.88901392 21.84434661]]
[2.3078461981905267, 0.5092312906233669, 22.318832293043414]
[[ 2.3078462   0.50923129 22.43532129]
 [ 2.3078462   1.44896229 22.04702429]
 [ 3.1216772   0.03936629 22.04702429]
 [ 1.4940152   0.03936629 22.04702429]]


0

In [4]:
text_to_write='''ITEM: TIMESTEP 
0
ITEM: NUMBER OF ATOMS
392
ITEM: BOX BOUNDS xy xz yz
-7.1604 14.3208 -7.1604 
0 12.402177 0
0 30.0 0
ITEM: ATOMS id type x y z '''